[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = 'let g:haskell_conceal = 0'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'gi1242/vim-tex-syntax'
on_ft = ['plaintex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
