[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['cpp']
hook_add = '''
let g:deoplete#sources#clang#libclang_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang'
let g:syntastic_cpp_compiler_options = ' -std=c++14'
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = 'let g:haskell_conceal = 0'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'gi1242/vim-tex-syntax'
on_ft = ['plaintex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
