[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = 'source ~/.config/nvim/plugins/denite_add.rc.vim'
hook_source ='source ~/.config/nvim/plugins/denite_source.rc.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
on_cmd = 'Defx'
hook_add = 'source ~/.config/nvim/plugins/defx_add.rc.vim'
hook_source = 'source ~/.config/nvim/plugins/defx_source.rc.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = 'source ~/.config/nvim/plugins/deol.rc.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = 'let g:haskell_conceal = 0'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
let g:rustfmt_autosave = 1
let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'gi1242/vim-tex-syntax'
on_ft = ['plaintex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rwd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xml', 'vue']
hook_add = '''
let g:closetag_filenames = '*.html,*.xml,*.vue'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'
'''
