[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
merged = 0
hook_add = 'source ~/.config/nvim/plugins/coc.rc.vim'

#[[plugins]]
#repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# update時: ":TSUpdate"
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source ~/.config/nvim/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'wombat'
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
let g:rainbow_conf = {
\    'guifgs': ['lightskyblue1', 'lightyellow', 'lightcyan', 'lightmagenta']
\}
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
let g:molokai_original = 1
let g:rehash256 = 1
autocmd ColorScheme * highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE gui=underline guibg=NONE
autocmd ColorScheme * highlight Normal     ctermbg=NONE guibg=NONE
autocmd ColorScheme * highlight LineNr     ctermbg=NONE guibg=NONE
autocmd ColorScheme * highlight SignColumn ctermbg=NONE guibg=NONE
autocmd ColorScheme * highlight Comment    ctermfg=81 guifg=#66D9EF
autocmd ColorScheme * highlight Visual     cterm=reverse gui=reverse
autocmd ColorScheme * highlight Delimiter  ctermfg=NONE guifg=NONE
colorscheme molokai
'''

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = 'let g:seiya_auto_enable = 1'

# for defx, need 'github.com/ryanoasis/nerd-fonts' and use 'NERD FONT'
[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
set guifont=DroidSansMono\ Nerd\ Font\ 12
'''

# for vim8
[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"
