[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = 'source ~/.config/nvim/plugins/denite_add.rc.vim'
hook_source ='source ~/.config/nvim/plugins/denite_source.rc.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
on_cmd = 'Defx'
hook_add = 'source ~/.config/nvim/plugins/defx_add.rc.vim'
hook_source = 'source ~/.config/nvim/plugins/defx_source.rc.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = 'source ~/.config/nvim/plugins/deol.rc.vim'

# need prettier
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['js', 'ts', 'tsx']
hook_add = '''
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
let g:prettier#autoformat_config_present = 1
let g:prettier#exec_cmd_path = substitute(system('which prettier'), "\n", "", "g")
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss Prettier
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_add = 'let g:haskell_conceal = 0'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
let g:goimports_simplify = 1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
let g:rustfmt_autosave = 1
let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'gi1242/vim-tex-syntax'
on_ft = ['plaintex']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rwd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xml', 'vue']
hook_add = '''
let g:closetag_filenames = '*.html,*.xml,*.vue'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'
'''
